REVOKE ALL ON DATABASE app1_db FROM PUBLIC;
REVOKE ALL ON DATABASE app2_db FROM PUBLIC;

GRANT CONNECT ON DATABASE app1_db TO app1_user;
GRANT ALL PRIVILEGES ON DATABASE app1_db TO app1_user;

GRANT CONNECT ON DATABASE app2_db TO app2_user;
GRANT ALL PRIVILEGES ON DATABASE app2_db TO app2_user;
